// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "hero": {
      "title": "Analyze the reliability of your future vehicle",
      "description": "Use our AI to get a complete analysis of reliability, common problems, and repair costs for any vehicle.",
      "searchPlaceholder": "Search for a brand…",
      "searchLabel": "Search for a car brand",
      "searchButton": "Search",
      "browseSpecs": "Browse specifications",
      "generations": "Generations",
      "models": "Models",
      "specs": "Spec sheets",
      "heroImageAlt": "Vehicle search illustration"
    },
    "aiFeatures": {
      "title": "Complete AI Analysis",
      "description": "Our artificial intelligence analyzes automotive market data to provide you with detailed information about each vehicle.",
      "reliability": "Reliability Score",
      "reliabilityDesc": "Get an overall reliability score based on user feedback and market data.",
      "problems": "Common Problems",
      "problemsDesc": "Discover frequent issues reported by owners of this model.",
      "costs": "Repair Costs",
      "costsDesc": "Estimate typical repair and maintenance costs for this vehicle.",
      "maintenance": "Maintenance Tips",
      "maintenanceDesc": "Receive personalized recommendations to keep your vehicle in good condition.",
      "buying": "Buying Advice",
      "buyingDesc": "Get tailored buying advice and points to check before purchasing.",
      "chat": "Interactive Chat",
      "chatDesc": "Ask questions about the vehicle and get instant answers.",
      "cta": "Search for a vehicle above to start the analysis"
    },
    "categories": {
      "title": "Car Categories",
      "description": "Find the car category that suits you from our car categories.",
      "types": {
        "suv": "SUV",
        "berline": "Sedan",
        "coupe": "Coupe",
        "cabriolet": "Convertible",
        "citadine": "City Car",
        "break": "Station Wagon"
      }
    },
    "pricing": {
      "title": "Our Plans",
      "description": "Tailored solutions for individuals and professionals",
      "billing": {
        "monthly": "Monthly",
        "annual": "Annual",
        "discount": "Save 10%"
      },
      "plans": {
        "basic": {
          "title": "Basic",
          "description": "For browsing and buying",
          "features": ["Browse listings", "Buy vehicles (private and dealers)"],
          "cta": "Sign up"
        },
        "pro_standard": {
          "title": "Pro Standard",
          "description": "Advanced security and verification",
          "features": ["VIN verification", "Damage history", "Premium support"],
          "cta": "Subscribe",
          "recommended": "Recommended"
        },
        "pro_premium": {
          "title": "Pro Premium",
          "description": "For professional dealerships",
          "features": [
            "All Pro Standard features",
            "Advanced analytics",
            "Priority support",
            "Custom branding"
          ],
          "cta": "Subscribe"
        },
        "featuresCount": "features"
      }
    },
    "benefits": {
      "title": "Benefits of Using Garage Finder",
      "description": "Garage Finder offers a range of benefits to help you streamline your garage operations and connect with buyers.",
      "visibility": {
        "title": "Increased Visibility",
        "description": "Reach a wider audience and get more visibility for your garage and parts."
      },
      "tools": {
        "title": "Time-Saving Tools",
        "description": "Streamline your garage operations with our suite of management tools."
      },
      "efficiency": {
        "title": "Improved Efficiency",
        "description": "Optimize your garage workflow and focus on serving your customers."
      },
      "transactions": {
        "title": "Smooth Transactions",
        "description": "Facilitate smooth and secure transactions between buyers and sellers."
      },
      "support": {
        "title": "Complete Support",
        "description": "Get dedicated support from our team to help you succeed."
      },
      "pricing": {
        "title": "Competitive Pricing",
        "description": "Enjoy affordable pricing plans to meet your garage's needs."
      }
    },
    "features": {
      "title": "Key Features",
      "description": "Garage Finder offers a comprehensive set of features to streamline your garage management and buying/selling experience.",
      "advancedInventory": {
        "title": "Advanced Inventory",
        "description": "Manage your inventory efficiently"
      },
      "smartSearch": {
        "title": "Smart Search",
        "description": "Find exactly what you need"
      },
      "enhancedSecurity": {
        "title": "Enhanced Security",
        "description": "Keep your data safe"
      },
      "marketAnalysis": {
        "title": "Market Analysis",
        "description": "Stay ahead of the market"
      },
      "optimize": {
        "title": "Optimize Your Business",
        "description": "Take your garage to the next level",
        "subtitle": "Discover how our features can help you grow",
        "benefits": [
          "Increased efficiency",
          "Better customer service",
          "Higher profits",
          "Streamlined operations"
        ],
        "cta": "Get Started"
      }
    }
  },
  "Header": {
    "navigation": {
      "menu": "Menu",
      "pro": "Pro",
      "specs": "Technical Sheet",
      "services": "Services",
      "search": "Search",
      "favorites": "My Favorites",
      "postAd": "Post an Ad"
    },
    "services": {
      "title": "Our Services",
      "description": "Our services are available to help you find or sell your vehicle",
      "accidentCheck": {
        "title": "Accident & Mileage Check",
        "description": "Check if your vehicle has had any accidents"
      },
      "registrationPrice": {
        "title": "Registration Price",
        "description": "Calculate your registration card price"
      }
    }
  },
  "CardDetails": {
    "description": "Description",
    "lastUpdate": "Last update",
    "details": "Details",
    "trim": "Trim",
    "brand": "Brand",
    "model": "Model",
    "mileage": "Mileage",
    "year": "Year",
    "gearbox": "Gearbox",
    "specifications": "Technical Specifications",
    "equipment": "Equipment",
    "fuelType": "Fuel Type",
    "color": "Color",
    "generation": "Generation",
    "serie": "Series",
    "options": "Options",
    "contactSeller": "Contact seller",
    "sendMessage": "Send message"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, fr {French} en {English} other {Unknown}}"
  },
  "RegisterForm": {
    "title": "Create an account",
    "or": "Or",
    "username": "Username",
    "usernamePlaceholder": "Enter your username",
    "email": "Email",
    "emailPlaceholder": "Enter your email",
    "password": "Password",
    "passwordPlaceholder": "********",
    "submit": "Sign up",
    "errors": {
      "usernameRequired": "Username is required",
      "invalidEmail": "Invalid email",
      "passwordLength": "Password must be at least 8 characters",
      "default": "Error, please try again"
    },
    "success": {
      "title": "Registration successful",
      "description": "You can now log in"
    }
  },
  "Search": {
    "labels": {
      "marque": "Brand",
      "model": "Model",
      "generation": "Generation",
      "localisation": "Location",
      "vehicleType": "Vehicle Type",
      "fuelType": "Fuel Type",
      "priceMin": "Min Price",
      "priceMax": "Max Price",
      "yearMin": "Min Year",
      "yearMax": "Max Year",
      "transmission": "Transmission",
      "kmMin": "Min Km",
      "kmMax": "Max Km"
    }
  },
  "AI": {
    "report": {
      "title": "Reliability Analysis",
      "loading": "Generating report...",
      "reliabilityScore": "Reliability Score",
      "commonProblems": "Common Problems",
      "repairCosts": "Cost Estimates",
      "maintenanceTips": "Maintenance Tips",
      "buyingAdvice": "Buying Advice"
    },
    "chat": {
      "title": "Ask Questions",
      "placeholder": "Ask for details about this vehicle...",
      "send": "Send"
    }
  },
  "Credits": {
    "title": "Buy Credits",
    "yourBalance": "Your Balance",
    "balanceDescription": "Use your credits to unlock vehicle technical sheets",
    "credits": "credits",
    "credit": "credit",
    "buyCredits": "Buy Credits",
    "popular": "Popular",
    "save": "Save",
    "unlockSpecs": "Unlock {count} technical sheets",
    "permanentAccess": "Permanent access to sheets",
    "noExpiration": "Credits never expire",
    "buy": "Buy",
    "accessRequired": "Access Required",
    "loginToAccess": "Log in to access this technical sheet",
    "login": "Log In",
    "unlockSpecification": "Unlock Technical Sheet",
    "unlockDescription": "This technical sheet is premium. Unlock it with your credits for permanent access.",
    "cost": "Cost",
    "unlock": "Unlock",
    "insufficientCredits": "Insufficient credits. Buy credits to continue.",
    "success": {
      "title": "Payment Successful",
      "description": "Your credits have been added to your account.",
      "creditsAdded": "Your credits are now available.",
      "viewBalance": "View Balance",
      "browseSpecs": "Browse Sheets"
    },
    "history": {
      "title": "Credits History",
      "transactions": "Transactions",
      "transactionsDescription": "History of your credit purchases and usage",
      "type": "Type",
      "description": "Description",
      "date": "Date",
      "amount": "Amount",
      "noTransactions": "No transactions",
      "error": "Error loading history",
      "types": {
        "PURCHASE": "Purchase",
        "CONSUMPTION": "Usage",
        "REFUND": "Refund",
        "BONUS": "Bonus"
      }
    }
  }
};
export default messages;