import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ReactQueryProvider } from "./react-query-provider";
import { Analytics } from "@vercel/analytics/react";
import { SessionProvider } from "next-auth/react";

import { Toaster } from "@/components/ui/toaster";

const font = Inter({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={font.className}>
        <SessionProvider>
          <ReactQueryProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
            <Analytics />
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
