import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ReactQueryProvider } from "./react-query-provider";
import { Analytics } from "@vercel/analytics/react";
import { Toaster } from "@/components/ui/sonner";
import GoogleAdsense from "@/lib/GoogleAdsense";
import React from "react";

const font = Inter({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={font.className}>
        <GoogleAdsense id="8946842704207401" />
        <NextIntlClientProvider>
          <ReactQueryProvider>
            {children}
            <Toaster />
            <Analytics />
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
