import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/components/footer";
import { ReactQueryProvider } from "./react-query-provider";
import { Analytics } from "@vercel/analytics/react";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/lib/auth";

import { getMessages } from "next-intl/server";
import GoogleAdsense from "@/lib/GoogleAdsense";

const font = Inter({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string; pathname: string };
}>) {
  const session = await auth();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={font.className}>
        <GoogleAdsense id="8946842704207401" />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReactQueryProvider>
            <SessionProvider session={session}>
              {children}
              <Toaster />
              <Footer />
              <Analytics />
            </SessionProvider>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
